### ISSUE TITLE
Running the main ipython script

### ISSUE THREAD

**Issue by danieladea** [fabvio/Cascade-LD#2]
Hi, your network seems promising and I'd love to see what it can do; however, I'm unable to run main.ipynb in jupiter. I get an error about matplotlib
AttributeError                            Traceback (most recent call last)
/usr/local/lib/python3.5/dist-packages/ipykernel/pylab/backend_inline.py in show(close, block)
     37             display(
     38                 figure_manager.canvas.figure,
---> 39                 metadata=_fetch_figure_metadata(figure_manager.canvas.figure)
     40             )
     41     finally:

/usr/local/lib/python3.5/dist-packages/ipykernel/pylab/backend_inline.py in _fetch_figure_metadata(fig)
    172     """Get some metadata to help with displaying a figure."""
    173     # determine if a background is needed for legibility
--> 174     if _is_transparent(fig.get_facecolor()):
    175         # the background is transparent
    176         ticksLight = _is_light([label.get_color()

/usr/local/lib/python3.5/dist-packages/ipykernel/pylab/backend_inline.py in _is_transparent(color)
    193 def _is_transparent(color):
    194     """Determine transparency from alpha."""
--> 195     rgba = colors.to_rgba(color)
    196     return rgba[3] < .5

AttributeError: module 'matplotlib.colors' has no attribute 'to_rgba'

 What versions of python and necessary libraries do you use to make it work?

**Comment by fabvio** [comment]
Hi, sorry for the late delay. The code is running with python 3.7.2, matplotlib 3.0.3 and Jupyter Notebook 5.6.0. Maybe you are using python2?
