### ISSUE TITLE
I am confused with some details in the paper and looking forward to your code for training

### ISSUE THREAD

**Issue by monsterlyg** [fabvio/Cascade-LD#3]

**Comment by fabvio** [comment]
Hi, unfortunately now I am busy with other deadlines and I don't have time to release the complete training script, but if you tell me your doubts I will be happy to clarify also with code snippets!

**Comment by monsterlyg** [comment]
I have been working on trivial things these days and myquestion before is about extracting the descriptor. Appreciatelly you have given the answer in another issue.
